---
- hosts: localhost
  vars_files:
    - config.yml

  roles: 
    - role: geerlingguy.mac.homebrew
      when: ansible_os_family == "Darwin" and homebrew_install
      tags:
        - macos

    - role: archlinux
      when: ansible_os_family == "Archlinux"
      tags:
        - archlinux

    - role: zsh
      when: zsh_install | bool
      tags:
        - zsh-install

    - role: dotfiles
      when: dotfiles_link | bool

    - role: neovim
      when: neovim_setup

    - role: languages
      when: languages_setup | bool 



  tasks:
    - debug:
        msg: 
          os_fam: "{{ ansible_facts['os_family'] }}"
          os_fam2: "{{ ansible_os_family }} "



